//
//  SettingsTableViewController.swift
//  Swol
//
//  Created by Pedro Giuliano Farina on 27/03/20.
//  Copyright © 2020 Pedro Giuliano Farina. All rights reserved.
//

import UIKit
import SwolBackEnd

public class SettingsTableViewController: UITableViewController {
    @IBOutlet weak var iCloudTableViewCell: SwitchTableViewCell!
    private var deleteAlert: UIAlertController = {
        let cont = UIAlertController(title: "Are you sure?".localized(), message: "This action will delete all your devices from iCloud. It can't be undone.".localized(), preferredStyle: .alert)
        let yesAction = UIAlertAction(title: "Yes".localized(), style: .destructive) { (_) in
            DataManager.shared(with: iCloudAccessManager.permission).deleteCloudData()
        }
        let noAction = UIAlertAction(title: "No".localized(), style: .cancel, handler: nil)

        cont.addAction(yesAction)
        cont.addAction(noAction)
        return cont
    }()

    public override func viewDidLoad() {
        iCloudTableViewCell.onOffChanged = { (onOffSwitch) in
            iCloudAccessManager.isEnabled = onOffSwitch.isOn
        }
    }

    public override func viewWillAppear(_ animated: Bool){
        iCloudTableViewCell.onOff.isOn = iCloudAccessManager.isEnabled
    }

    public override func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if indexPath.section == 0 {
            if indexPath.row == 0 {
                iCloudTableViewCell.isOn = !iCloudTableViewCell.isOn
            } else if indexPath.row == 1 {
                self.present(deleteAlert, animated: true)
            }
        } else if indexPath.section == 1 {
            if indexPath.row == 0 {
                self.performSegue(withIdentifier: "tutorial", sender: self)
            }
        } else if indexPath.section == 2  {
            if indexPath.row == 0 {
                let alertController = UIAlertController(title: "Enter the new devices".localized(),
                                                        message: "This text can be generated by exporting the devices.".localized(),
                                                        preferredStyle: .alert)
                alertController.addTextField(configurationHandler: nil)
                alertController.addAction(UIAlertAction(title: "Add".localized(),
                                                        style: .default,
                                                        handler: { [weak alertController] (_) in
                                                            let fallbackAlert = UIAlertController(title: "Oops!".localized(),
                                                                                                  message: "Unable to import devices.".localized(),
                                                                                                  preferredStyle: .alert)
                                                            fallbackAlert.addOkAction()
                                                            do {
                                                                let jsonDecoder = JSONDecoder()
                                                                guard let jsonString = alertController?.textFields?.first?.text,
                                                                      let jsonData = jsonString.data(using: .utf8),
                                                                      let devices = try? jsonDecoder.decode([CodableDevice].self, from: jsonData) else {
                                                                    self.present(fallbackAlert, animated: true)
                                                                    return
                                                                }
                                                                for device in devices {
                                                                    if let name = device.name,
                                                                       let address = device.address,
                                                                       let mac = device.mac {
                                                                        try? DataManager.shared(with: iCloudAccessManager.permission).registerDevice(
                                                                            name: name,
                                                                            address: address,
                                                                            macAddress: mac,
                                                                            port: device.port)
                                                                    }
                                                                }
                                                            }
                                                        }))
                alertController.addCancelAction()
                alertController.popoverPresentationController?.sourceView = tableView.cellForRow(at: indexPath) ?? tableView
                self.present(alertController, animated: true)
            } else if indexPath.row == 1 {
                let jsonEncoder = JSONEncoder()
                let devicesString: String?
                if let jsonData = try? jsonEncoder.encode(DataManager.shared(with: iCloudAccessManager.permission).codableDevices),
                   let json = String(data: jsonData, encoding: .utf8) {
                    devicesString = json
                } else {
                    devicesString = nil
                }
                let controller: UIViewController
                if let devicesString = devicesString, devicesString.count != 2 {
                    controller = UIActivityViewController(activityItems: [devicesString], applicationActivities: nil)
                } else {
                    let alertController = UIAlertController(title: "Oops!".localized(),
                                                            message: "You have no devices yet. Create one to export.".localized(),
                                                            preferredStyle: .alert)
                    alertController.addOkAction()
                    controller = alertController
                }
                controller.popoverPresentationController?.sourceView = tableView.cellForRow(at: indexPath) ?? tableView
                self.present(controller, animated: true)
            }
        }

        tableView.deselectRow(at: indexPath, animated: true)
    }
}
